import { Order, Status } from "../../types/order";

// export const orders: Order[] = [
//   {
//     order_id: "12345",
//     garmentId: "898989",
//     client: "BAC Costa Rica",
//     quantity: "100",
//     status: Status.IN_PROFRESS,
//     receivedDate: new Date(),
//     completedDate: new Date(),
//     deliveryDate: new Date(),
//     totalProcessingTime: 48,
//   },
//   {
//     order_id: "12345",
//     garmentId: "898989",
//     client: "BAC Costa Rica",
//     quantity: "100",
//     status: Status.IN_PROFRESS,
//     receivedDate: new Date(),
//     completedDate: new Date(),
//     deliveryDate: new Date(),
//     totalProcessingTime: 48,
//   },
//   {
//     order_id: "12345",
//     garmentId: "898989",
//     client: "BAC Costa Rica",
//     quantity: "100",
//     status: Status.IN_PROFRESS,
//     receivedDate: new Date(),
//     completedDate: new Date(),
//     deliveryDate: new Date(),
//     totalProcessingTime: 48,
//   },
//   {
//     order_id: "12345",
//     garmentId: "898989",
//     client: "BAC Costa Rica",
//     quantity: "100",
//     status: Status.IN_PROFRESS,
//     receivedDate: new Date(),
//     completedDate: new Date(),
//     deliveryDate: new Date(),
//     totalProcessingTime: 48,
//   },
//   {
//     order_id: "12345",
//     garmentId: "898989",
//     client: "BAC Costa Rica",
//     quantity: "100",
//     status: Status.IN_PROFRESS,
//     receivedDate: new Date(),
//     completedDate: new Date(),
//     deliveryDate: new Date(),
//     totalProcessingTime: 48,
//   },
//   {
//     order_id: "12345",
//     garmentId: "898989",
//     client: "BAC Costa Rica",
//     quantity: "100",
//     status: Status.IN_PROFRESS,
//     receivedDate: new Date(),
//     completedDate: new Date(),
//     deliveryDate: new Date(),
//     totalProcessingTime: 48,
//   },
//   {
//     order_id: "12345",
//     garmentId: "898989",
//     client: "BAC Costa Rica",
//     quantity: "100",
//     status: Status.IN_PROFRESS,
//     receivedDate: new Date(),
//     completedDate: new Date(),
//     deliveryDate: new Date(),
//     totalProcessingTime: 48,
//   },
//   {
//     order_id: "12345",
//     garmentId: "898989",
//     client: "BAC Costa Rica",
//     quantity: "100",
//     status: Status.IN_PROFRESS,
//     receivedDate: new Date(),
//     completedDate: new Date(),
//     deliveryDate: new Date(),
//     totalProcessingTime: 48,
//   },
// ];
